language: go
go:
 - 1.5.3

install:
 - go get github.com/constabulary/gb/...
 - go get github.com/alecthomas/gometalinter

before_script:
 - make dist
 - gometalinter --install --update
 - export GOPATH=$HOME/gopath:$HOME/gopath/src/github.com/skizzehq/skizze/:$HOME/gopath/src/github.com/skizzehq/skizze/vendor

script:
 - gometalinter ./src/* -D gocyclo -D gotype -D dupl --deadline=120s
 - make test
